== History of Fat Loss

It is common sense and obvious to me people have been dieting since the invention of the mirror. Vanity is nothing new, it simply has become magnified over time.

Today experts tell us lean people live longer and are more productive in their daily lives. For this reason, millions have embarked upon some sort of weight loss program. Although millions diet and exercise to live longer or to feel better and have more energy, my guess is the majority do so to look better. We aspire to the lean image portrayed by those we see on television, in print ads, and in movies.

Years ago, people who wanted to lose fat did so based upon a very limited amount of information. Before the invention of the word "calorie" people lost weight by fasting. Fasting was introduced to mankind by God. The Jews fast, as do the Christians, and Muslims. All do so because God told the prophets that abstaining from food was good for the soul as well as the physical body. A common physical change that all three groups noticed was a loss in weight, a decrease in body fat. Thus, to lose weight, the first dieter would abstain from food and drink water. It was then, and is today, a proven way to lose fat, albeit an extreme approach.

When a person abstains from food, the body has to break down body tissue to use for survival. Most of this fuel comes from stored energy in the form of body fat reserves. Unfortunately, a severe fast also is a dangerous fast as the body...