== History of Fat Loss

It is common sense and obvious to me people have been dieting since the invention of the mirror. Vanity is nothing new, it simply has become magnified over time.

Today experts tell us lean people live longer and are more productive in their daily lives. For this reason, millions have embarked upon some sort of weight loss program. Although millions diet and exercise to live longer or to feel better and have more energy, my guess is the majority do so to look better. We aspire to the lean image portrayed by those we see on television, in print ads, and in movies.

Years ago, people who wanted to lose fat did so based upon a very limited amount of information. Before the invention of the word "calorie" people lost weight by fasting. Fasting was introduced to mankind by God. The Jews fast, as do the Christians, and Muslims. All do so because God told the prophets that abstaining from food was good for the soul as well as the physical body. A common physical change that all three groups noticed was a loss in weight, a decrease in body fat. Thus, to lose weight, the first dieter would abstain from food and drink water. It was then, and is today, a proven way to lose fat, albeit an extreme approach.

When a person abstains from food, the body has to break down body tissue to use for survival. Most of this fuel comes from stored energy in the form of body fat reserves. Unfortunately, a severe fast also is a dangerous fast as the body...

also calls upon other tissues to be used as fuel. With fasting, the body chooses a mixture of stored body fat as fuel and lean body mass. Lean body mass is readily tapped as fuel. Just as the body taps body fat and breaks it down to use it as energy, it can do the same with muscle and organs. When deprived of food, the body can easily break down the heart, the liver, and other organs to make fuel. The body will also rip apart the muscles throughout the body to make fuel during a starvation fast. While fat is burned up quickly as fuel, muscle and organs are also burned. This can lead to exhaustion and eventually death. So, we can conclude, the fast, while spiritually advantageous, isn't exactly the smartest approach to losing fat.

Once people figured out prolonged fasting worked, but the negative was death, they began to alter the fasting approach to weight loss. Thus, the modified fast was born. The modified fast involved abstaining from food completely for as long as you could, and when you finally broke down, your willpower crushed and your appetite screaming in high gear, you would eat. Some would eat a small amount and drink a ton of water to suppress the appetite, but others would go crazy, break down, and eat as if it was their last meal on earth, probably negating any fat lost during a few days of fasting.

With the breakthroughs in science, man "discovered" the calorie and the never ending task of tabulating numbers, keeping records, and avoiding large portions began. However, the dieter did not know how many calories he required in a day, so in hopes of losing fat, and with little knowledge, he resorted to a method that is still prevalent today. That method is, "If you are not sure how many calories you should be eating to lose weight, just take the conservative route, and eat less." For many, the magical number of 1000 seemed to be low enough to work, and many who followed a diet that yielded only 1000 calories in a day lost weight.

Many who chose the 1000 calorie a day approach soon discovered what scientists would prove many years later, the dreaded dieting plateau. Science has shown that when calories are restricted, the body compensates by obtaining energy from stored body fat. But, as calories remain low for an extended...