== Chapter One: Everything You Need To Know On Weight Loss

Why another book about weight loss, losing body fat, and diet? Surely, there are enough!

Just peruse your local book super store, and you will soon become overwhelmed with the amount of books guiding, prescribing, and selling the latest tips, info, research, ideas, potions, pills and promises pertaining to losing fat.

I find much of the weight loss information to be conflicting, confusing, overwhelming, and ultimately can do more harm than good. For example, we have the "rice diet" and the "fruit diet." Some say fruit turns to fat while others only eat fruits before noon. Fruit can turn to fat compared to what, donuts? I think not! I never saw anyone sit down and eat too much fruit, say 3 apples a pear and a banana.

However, we've all, at some time or another, sat down in front of the TV and gobbled down a whole pizza, or a box of cookies, or a mound of ice cream. Is fruit fattening? You're smart, you tell me. For those who prescribe eating fruit only before noon, I say this, "What if you work the late shift and do not wake up until noon, then what?"

Of course, the low fat diet, the incredible dietary revelation started by Pritikin works. Or does it? The low fat approach to losing weight prescribes lowering your intake of dietary fat to less than 10% of your total calories. The food industry has responded by making nearly every food product available with no fat or little fat added. Now, we can eat fat free pretzels, fat free potato chips, fat free ice cream, fat free pizza...

fat free tuna sandwiches, fat free cookies, and the list continues. My question is this: With so much to choose from, why are we Americans, on average, fatter than ever?

Some weight loss books blame your laziness. The authors of these books sound something like this: "Exercise burns calories, so performing enough exercise will keep a person lean or promote fat loss in everyone." Sorry.

While exercise can help, it is not the full story, the end all. What you eat, the amount of total calories you eat, and the types of foods you eat also has an effect on fat storage. Some people can get very lean with exercise, but others should rely more on diet. Furthermore, there are more gyms, health clubs, resorts, personal trainers, exercise machines, and gadgets than ever. So what's the scoop? How is it, we are fatter than ever? Sure, there are lots of awesome and incredible bodies around, but as a whole, the population is pretty sloppy.

I know we are failing the fat test when I consistently see fat kids at malls, schools, and church. Sure there were some chunky kids around when I was young. Every school had its fat little kid who was the brunt of jokes and picked on, but there are so many now!

There are fat loss pills, creams, drinks, gurus, prescription pills, appetite suppressants, and therapy. There's late night infomercials, gadgets, clinics, medical weight loss programs, Jenny Craig, Weight Watchers, Slimfast, MetRx, Ensure. And if that is not enough, we are bombarded with stars, who have always appeared lean, fit and trim, hocking everything from a thigh toning machine to an indoor roller blading device.

I am sure you've seen those ab machines on T.V. too. I'll let you in on a secret. First, the models used for the ab machines probably never in their lives used these machines. Second, the infomercials imply you will be able to achieve some awesome looking abs by using the ab machine. I highly doubt that would occur. To get the abs the model has, you would need to eat the right diet to strip away all the fat covering the abdominal region to allow the abs to shine. Next, you would have to build the abdominals with exercise.

P.T. Barnum was the founder to the phrase, "There is a sucker born every minute." This was true in his day, and still holds true today. Let me tell you how crazy the diet and exercise industry is.

A few years ago, I had a meeting with a very prominent publisher of an exercise magazine. Over a business lunch, he told me, "Chris, if you want to make money, you should write a diet book, but not just any old diet and exercise book. Take an odd approach, make it really gimmicky and outrageous. Promise overnight transformations, promise instant results, promise the reader that this diet is top secret, one used by Hollywood stars and top professional bodybuilders. Tell the reader you consult with Pro Athletes, movie stars, even politicians."

As I grew skeptical and as my feeling of respect for this individual suddenly began to change as he spoke, he added, "The crazier the promises sound, the more people will buy. The buying public is just so damn naive, confused and desperate, they'll try anything!"

After that conversation, I called my wife and we agreed that if I ever wrote a book, it would be the exact opposite of the rich publisher's recommendation...