== History of Fat Loss

It is common sense and obvious to me people have been dieting since the invention of the mirror. Vanity is nothing new, it simply has become magnified over time.

Today experts tell us lean people live longer and are more productive in their daily lives. For this reason, millions have embarked upon some sort of weight loss program. Although millions diet and exercise to live longer or to feel better and have more energy, my guess is the majority do so to look better. We aspire to the lean image portrayed by those we see on television, in print ads, and in movies.

Years ago, people who wanted to lose fat did so based upon a very limited amount of information. Before the invention of the word "calorie" people lost weight by fasting. Fasting was introduced to mankind by God. The Jews fast, as do the Christians, and Muslims. All do so because God told the prophets that abstaining from food was good for the soul as well as the physical body. A common physical change that all three groups noticed was a loss in weight, a decrease in body fat. Thus, to lose weight, the first dieter would abstain from food and drink water. It was then, and is today, a proven way to lose fat, albeit an extreme approach.

When a person abstains from food, the body has to break down body tissue to use for survival. Most of this fuel comes from stored energy in the form of body fat reserves. Unfortunately, a severe fast also is a dangerous fast as the body...

also calls upon other tissues to be used as fuel. With fasting, the body chooses a mixture of stored body fat as fuel and lean body mass. Lean body mass is readily tapped as fuel. Just as the body taps body fat and breaks it down to use it as energy, it can do the same with muscle and organs. When deprived of food, the body can easily break down the heart, the liver, and other organs to make fuel. The body will also rip apart the muscles throughout the body to make fuel during a starvation fast. While fat is burned up quickly as fuel, muscle and organs are also burned. This can lead to exhaustion and eventually death. So, we can conclude, the fast, while spiritually advantageous, isn't exactly the smartest approach to losing fat.

Once people figured out prolonged fasting worked, but the negative was death, they began to alter the fasting approach to weight loss. Thus, the modified fast was born. The modified fast involved abstaining from food completely for as long as you could, and when you finally broke down, your willpower crushed and your appetite screaming in high gear, you would eat. Some would eat a small amount and drink a ton of water to suppress the appetite, but others would go crazy, break down, and eat as if it was their last meal on earth, probably negating any fat lost during a few days of fasting.

With the breakthroughs in science, man "discovered" the calorie and the never ending task of tabulating numbers, keeping records, and avoiding large portions began. However, the dieter did not know how many calories he required in a day, so in hopes of losing fat, and with little knowledge, he resorted to a method that is still prevalent today. That method is, "If you are not sure how many calories you should be eating to lose weight, just take the conservative route, and eat less." For many, the magical number of 1000 seemed to be low enough to work, and many who followed a diet that yielded only 1000 calories in a day lost weight.

Many who chose the 1000 calorie a day approach soon discovered what scientists would prove many years later, the dreaded dieting plateau. Science has shown that when calories are restricted, the body compensates by obtaining energy from stored body fat. But, as calories remain low for an extended...

period of time, the body makes another adaptive response. With prolonged calorie restriction or with severe calorie restriction, the body will begin to conserve calories. In time the 1000 calorie approach fails because the body, not wanting to die as happens in a severe and long fast, but having enough calories to survive, will make the most out of the 1000 calories by radically slowing down the rate at which it burns those 1000 calories. The result is fat is lost on a very low calorie approach, but the diet ultimately ceases to work like it did in the beginning.

Early research into metabolism and nutrition revealed many physiological understandings that dieters tried to use to enable them to lose fat. From day one, dieters have realized that eating less leads to weight loss. However, astute dieters realized the limitations of the 1000 calorie diet. Research began to prove that with a caloric restriction, body protein, specifically in the form of muscle mass was also being shed along with body fat. To combat this, dieters put a simple twist to the 1000 calorie diet. They ate all the calories from protein foods. The idea was simple. Count calories and limit the total to 1000, but eat only protein foods. The 1000 calories is low enough to cause the body to shed fat and eating more protein would prevent the body from using muscle as fuel. The mind set was simple. Flood the body with extra protein foods like meats, cheese, pork, hamburg, and chicken, but limit the caloric intake. The extra protein will keep the body from tapping muscle as fuel since it has the raw material or protein it needs in the foods. This worked better than fasting but it lacked variety and was just too difficult to maintain even for those who had the greatest willpower.

Around the early 1900's, scientists began looking into the reason why people overate. Scientists realized if people ate less, they would lose weight. Thus began the search for effective diet pills. The first diet pills focused on suppressing the appetite so less food would be consumed. Inventions like benzocaine were common. Placed upon the tongue, benzocaine would dull the taste buds and leave a tingling and weird sensation in the mouth which scientists hoped would

suppress the appetite. It worked for some, and failed for others. Similar success probably could be reached by washing your mouth out with soap every time you felt hungry. Surely, any foul substance that alters the sense of taste could keep a person from eating, no matter what the substance.

Other approaches included suppressing the appetite by stimulating the brain. This was initially accomplished with the administration of amphetamines - speed. Speed seems to suppress appetite by stimulating the appetite center of the brain. Plus, it fights fatigue by stimulating the nervous system. So far, it sounds like a monumental discovery and aid for dieters. You lose weight by eating less and you have plenty of energy. Unfortunately, as with many drugs, they work too good. Over stimulating the nervous system can lead to many maladies like schizophrenia, paranoia, irritability, inability to think clearly, and total exhaustion. Other drugs have been developed to decrease the appetite. Most exert strong stimulatory effects upon the nervous system but are much safer than pure speed. These drugs are similar to speed in their ability to suppress the appetite though they have been altered to have lesser overall body stimulating effects. Therefore, they are believed to be much safer. I will discuss many of them in the Chapter 15 on drugs.

At one time, drugs to increase the amount of calories burned were popular among the medical profession. Thyroid hormones govern the amount of energy the body uses in any given day. Supplemental thyroid could increase the metabolic rate but the body can readily adapt to the artificially high amounts of thyroid a patient is using. In healthy individuals, the body releases thyroid hormone into the blood and this is converted into a more active form that the body tissues use. When a patient, in hopes of shedding fat, swallows thyroid medication, the body eventually responds and adapts by slowing the conversion of the artificial hormone to the more active form in the body. Furthermore, the body's own release of this hormone is suppressed. Any increase in metabolism does not last. Those who try to drastically increase thyroid medication to force the body to increase the metabolism,

ultimately fail, as high amounts of thyroid will exert effects similar to a modified fast. Fat is lost but muscle tissue and organs are destroyed and broken down to be used as fuel.
Scientists soon discovered a special phenomena that occurs with food intake called thermogenesis. Thermogenesis is a fancy word for heat. Foods are really forms of energy. When food is eaten the body breaks down the fuel from the foods to obtain this energy to maintain life and to do work. The fate of this energy is three fold. Energy can be used up by the body, it can be stored as muscle glycogen to be used at a later date or it can be stored as body fat. The third fate of energy derived from food is it can be "wasted as heat." The body is always producing heat, much like a furnace. When foods are consumed the body temperature rises and some of the calories from the foods we eat are simply burned off as heat leaving less "net" calories available for the body, the muscle cells and fat cells. Some foods exert a strong thermic effect while others do not. Specifically, protein foods exert the greatest thermic effect. Roughly 20% of the calories derived from protein foods are not available to be used by the body because they are burned off as body heat. Of course, dieters adopted this fact, and once again, protein became the dieter's choice food. People ate a lot of protein hoping it would have a thermogenic "over-drive" effect. As with any diet that is lower in calories, the approach worked to some degree, mainly due to a total lower caloric intake.
Over time, as dieters failed in their quest for a lean body, psychologists postulated the theory that people overeat or under eat due to their emotional state. Some studies showed a correlation between depression and overeating. Psychologists reasoned a person could only free themselves from overeating with intensive therapy. Once the underlying psychological problem was found and treated, a patient would resume eating normally. While therapy may be helpful for some, it did not accommodate the fact that millions are overweight who seem to be perfectly content in their lives, and many can not lose weight who have undertaken years of exhaustive therapy.
To some degree, I have been involved and infatuated with