== Type of Calories

Calories are derived from foods and there are three types or sub groups of calories. They are carbohydrates, proteins and fat.

Carbohydrates are derived from non animal foods. Examples of healthier carbohydrates include rice, pasta, beans, breads, potatoes, yams and fruit. Other carbohydrates, sometimes called "manufactured carbs" include pretzels, low fat cakes, cookies and related items. Of course, desserts are full of carbohydrates found in the flour and sugar and, in most cases, they're loaded with fat. For our purpose, we're trying to differentiate, "what's a pure carbohydrate".

All carbohydrate foods are eventually digested, broken down and absorbed as sugar - sometimes called blood glucose. Technically, there's not much of a difference eating rice, potatoes or candy. All three dissolve and digest into a simple form of sugar called glucose.

The body keeps a tight check on the amount of sugar in the blood. For the body to function normally, the **concentration** of sugar within the blood remains fairly stable or "normal" between 70 mg/100 ml to 110 mg/100 ml of blood. In other words, the body prefers a sugar range of 70-110 mgs of glucose within a millimeter of blood. Still, to uncomplicate it a bit further, simply think of the 70-110 range as something that is quite normal and a guideline the

body has self imposed to keep it functioning at normal levels. One more thing; as sugar levels rise towards 110, and especially if sugar levels rise above 110, the body will attempt to reach a state of homeostasis - or a "balanced state" by releasing a "clearing" or "storage" hormone which whisks the excess sugar out of the blood and stores it into muscle tissue or fat tissue. On the other hand, when sugar levels approach 70, or fall below 70, the body releases a "liberating" or "breakdown" hormone which pulls sugar out of muscle tissue and drags it back into the blood. The storage hormone is called **insulin** while its opposing hormone, the liberator is called **glucagon.** It both cases, there exists somewhat of a tug-o-war where the body throws into action insulin **or** glucagon to keep blood glucose levels in a comfortable zone of 70-110.

To move on, we have to make a few assumptions, one being the 180 pounder will need 1800 calories a day - with no activity, *at complete and absolute rest.* Sure the 1800 calorie guestimate is not dead on and 100% accurate, but it's darn close, more than "in the ballpark." The 180 pounder who sits all day and remains completely inactive will need approximately 1800 calories to maintain his weight, to maintain his muscle mass and to keep the organs healthy. At 1800 calories a day, the 180 pounder would likely stay within a 70-110 range with regards to blood sugar levels, though likely closer to the lower end of 70.

When more calories are consumed than the body needs each day, and especially carbohydrate calories, the amount of sugar in the blood rises. When blood sugar levels rise, the body will kick up its production of insulin and store some of the carbohydrates so they can be used later. In general, the body stores the excess carbohydrates in the muscles as muscle glycogen or in the liver as liver glycogen. Glycogen is really nothing more than a **storage tank for sugar.** When sugar levels in the blood rise above 110, the body begins to pack away the excess sugar in these reserves. To a smaller degree, the body is capable of storing excess sugar as body fat as we'll see later. Though excess sugar from the blood is

commonly whisked away and stored as muscle or liver glycogen, the tanks that capture sugar within both the muscles and liver are limited. In simple terms, the muscles or liver can only hold onto "so much" sugar. **Once these tanks are full, excess carbs will be stored as body fat.**

For example, the 180 pounder eating 3000 calories a day, yet remaining completely inactive, will experience chronically high sugar levels within the blood from munching down carbohydrate calories beyond what he needs each day. After a day or so, his muscles and liver will quickly fill up with glucose, forming "full to the brim" amounts of glycogen. At that point, all extra carbohydrates will be stored as body fat.
*In most cases, if glycogen stores are not full, excess carbs will be deposited as glycogen.* If glycogen stores are full, excess carbs will be stored as fat.

When calories remain closer to 1800 in the completely inactive 180 pounder, the concentration of sugar within the blood falls closer to 70 and very easily can fall below 70. When this occurs, the body outputs glucagon which permits sugar to flow out of glycogen and liver reserves. In effect, glucagon causes muscles and liver to "give up" sugar, to restore blood sugar levels closer to a normal range of 70-110. If calories and carbohydrates stay low for an extended period of time, the glucagon will also begin to liberate fatty acids from fat cells. Thus, glucagon can not only drag sugar from glycogen stores, but it can promote the breakdown of fat cells so fatty acids can be used as fuel.

[.text-center]
**Protein**

Protein is derived from animal foods; chicken, turkey, meats, lamb, fish and all dairy products are complete sources of protein. These foods are commonly referred to as "complete" because they contain all of the essential amino acids, the tiny building blocks required for health. The protein found in non animal sources of food are called "incomplete" proteins. Incomplete proteins lack 1 or more of the essential amino acids.

Thus, proteins supply the building blocks of life called amino acids. All animal source protein foods are digested, broken down and absorbed as amino acids akin to the way carbohydrates are broken down into glucose. Amino acids are to proteins as glucose is to carbohydrates. Aminos are the "tiny fragments" of protein while glucose is the "tiny fragments" of carbohydrates.

Amino acids are used for thousands, likely multi-millions, of reactions in the body. Low protein-low calories diets promote self catabolism. In other words, a low calorie diet that is also too low in protein causes the body to scavenge for the aminos necessary for everything from immune support, hormone production, to strong teeth and healthy hair. If the body is low on protein and there is insufficient amino acids in what's termed "amino acid pools"- temporary waiting pins for amino acids consumed from recently eaten protein foods - the body enters a state of catabolism. Catabolism is derived from the word catabolic which is really a fancy way to say, "canabalism." That is, when calories are low and protein intake is low, the body, in dire need of essential amino acids to maintain life itself, will begin to tear apart it's muscle tissue and organs as both are literally comprised or "made up of" amino acids. Interestingly, the body will, with the help of glucagon, take those amino acids that have been torn apart from muscle tissue and convert the aminos into glucose! Called gluconeogenesis, its sort of a survival mechanism in two ways.

**1.** First, when calories are way too low, the body can make sugar to keep itself alive by catabolising/canabolising its own muscle tissue into glucose. Specifically, this catabolism of muscle is used to fuel the brain. The brain is the "crown jewel" of all human organs. It's what makes us human and distinctly different from animals and it is glucose that keeps the brain alive. Survival wise, the body can eat up its own tissue to make sugar. Why? So a starving human can decide what to do next, to put an end to such hunger. Crude. But true.