== Capítulo Uno: Todo lo que necesitas saber sobre la pérdida de peso

¿Por qué otro libro sobre la pérdida de peso, la pérdida de grasa corporal y la dieta? ¡Seguro que ya hay suficientes!

Basta con echar un vistazo a la gran librería de su localidad para sentirse abrumado por la cantidad de libros que orientan, prescriben y venden los últimos consejos, información, investigaciones, ideas, pociones, pastillas y promesas relativas a la pérdida de grasa.

Me parece que gran parte de la información sobre la pérdida de peso es contradictoria, confusa, abrumadora y, en última instancia, puede hacer más daño que bien. Por ejemplo, tenemos la "dieta del arroz" y la "dieta de la fruta". Algunos dicen que la fruta se convierte en grasa, mientras que otros solo comen fruta antes del mediodía. ¿La fruta puede convertirse en grasa en comparación con qué, con los donuts? ¡Creo que no! Nunca he visto a nadie sentarse y comer demasiada fruta, digamos 3 manzanas, una pera y un plátano.

Sin embargo, todos nosotros, en algún momento, nos hemos sentado frente al televisor y engullido una pizza entera, o una caja de galletas, o una montaña de helado. ¿Engorda la fruta? Eres inteligente, dímelo tú. A los que prescriben comer fruta solo antes del mediodía, les digo esto: "¿Y si trabajas en el turno de noche y no te despiertas hasta el mediodía, entonces qué?".

Por supuesto, la dieta baja en grasas, la increíble revelación dietética iniciada por Pritikin, funciona. ¿O no? El enfoque bajo en grasas para perder peso prescribe reducir la ingesta de grasa dietética a menos del 10% del total de calorías. La industria alimentaria ha respondido haciendo que casi todos los productos alimentarios estén disponibles sin grasa o con poca grasa añadida. Ahora, podemos comer pretzels sin grasa, patatas fritas sin grasa, helado sin grasa, pizza sin grasa...