== Capítulo Uno: Todo lo que necesitas saber sobre la pérdida de peso

¿Por qué otro libro sobre la pérdida de peso, la pérdida de grasa corporal y la dieta? ¡Seguro que ya hay suficientes! [cite: 1127, 1129]

Basta con echar un vistazo a la gran librería de su localidad para sentirse abrumado por la cantidad de libros que orientan, prescriben y venden los últimos consejos, información, investigaciones, ideas, pociones, pastillas y promesas relativas a la pérdida de grasa. [cite: 1130]

Me parece que gran parte de la información sobre la pérdida de peso es contradictoria, confusa, abrumadora y, en última instancia, puede hacer más daño que bien. [cite: 1131] Por ejemplo, tenemos la "dieta del arroz" y la "dieta de la fruta". [cite: 1132] Algunos dicen que la fruta se convierte en grasa, mientras que otros solo comen fruta antes del mediodía. [cite: 1133] ¿La fruta puede convertirse en grasa en comparación con qué, con los donuts? ¡Creo que no! [cite: 1134] Nunca he visto a nadie sentarse y comer demasiada fruta, digamos 3 manzanas, una pera y un plátano. [cite: 1135]

Sin embargo, todos nosotros, en algún momento, nos hemos sentado frente al televisor y engullido una pizza entera, o una caja de galletas, o una montaña de helado. [cite: 1136] ¿Engorda la fruta? Eres inteligente, dímelo tú. A los que prescriben comer fruta solo antes del mediodía, les digo esto: "¿Y si trabajas en el turno de noche y no te despiertas hasta el mediodía, entonces qué?". [cite: 1137]

Por supuesto, la dieta baja en grasas, la increíble revelación dietética iniciada por Pritikin, funciona. ¿O no? [cite: 1138] El enfoque bajo en grasas para perder peso prescribe reducir la ingesta de grasa dietética a menos del 10% del total de calorías. [cite: 1139] La industria alimentaria ha respondido haciendo que casi todos los productos alimentarios estén disponibles sin grasa o con poca grasa añadida. [cite: 1140] Ahora, podemos comer pretzels sin grasa, patatas fritas sin grasa, helado sin grasa, pizza sin grasa... [cite: 1141]