== Historia de la pérdida de grasa

Es de sentido común y obvio para mí que la gente ha estado haciendo dieta desde la invención del espejo. La vanidad no es nada nuevo, simplemente se ha magnificado con el tiempo.

Hoy en día, los expertos nos dicen que las personas delgadas viven más tiempo y son más productivas en su vida diaria. Por esta razón, millones de personas se han embarcado en algún tipo de programa de pérdida de peso. Aunque millones de personas hacen dieta y ejercicio para vivir más o para sentirse mejor y tener más energía, supongo que la mayoría lo hace para verse mejor. Aspiramos a la imagen delgada proyectada por quienes vemos en la televisión, en anuncios impresos y en las películas.

Hace años, las personas que querían perder grasa lo hacían basándose en una cantidad muy limitada de información. Antes de la invención de la palabra "caloría", la gente perdía peso mediante el ayuno. El ayuno fue introducido a la humanidad por Dios. Los judíos ayunan, al igual que los cristianos y los musulmanes. Todos lo hacen porque Dios les dijo a los profetas que abstenerse de comer era bueno tanto para el alma como para el cuerpo físico. Un cambio físico común que los tres grupos notaron fue una pérdida de peso, una disminución de la grasa corporal. Por lo tanto, para perder peso, el primer "dietero" se abstenía de comer y bebía agua. Era entonces, y es hoy, una forma probada de perder grasa, aunque sea un enfoque extremo.

Cuando una persona se abstiene de comer, el cuerpo tiene que descomponer el tejido corporal para utilizarlo para la supervivencia. La mayor parte de este combustible proviene de la energía almacenada en forma de reservas de grasa corporal. Desafortunadamente, un ayuno severo también es un ayuno peligroso, ya que el cuerpo...

