== Historia de la pérdida de grasa

Es de sentido común y obvio para mí que la gente ha estado haciendo dieta desde la invención del espejo. La vanidad no es nada nuevo, simplemente se ha magnificado con el tiempo.

Hoy en día, los expertos nos dicen que las personas delgadas viven más tiempo y son más productivas en su vida diaria. Por esta razón, millones de personas se han embarcado en algún tipo de programa de pérdida de peso. Aunque millones de personas hacen dieta y ejercicio para vivir más o para sentirse mejor y tener más energía, supongo que la mayoría lo hace para verse mejor. Aspiramos a la imagen delgada proyectada por quienes vemos en la televisión, en anuncios impresos y en las películas.

Hace años, las personas que querían perder grasa lo hacían basándose en una cantidad muy limitada de información. Antes de la invención de la palabra "caloría", la gente perdía peso mediante el ayuno. El ayuno fue introducido a la humanidad por Dios. Los judíos ayunan, al igual que los cristianos y los musulmanes. Todos lo hacen porque Dios les dijo a los profetas que abstenerse de comer era bueno tanto para el alma como para el cuerpo físico. Un cambio físico común que los tres grupos notaron fue una pérdida de peso, una disminución de la grasa corporal. Por lo tanto, para perder peso, el primer "dietero" se abstenía de comer y bebía agua. Era entonces, y es hoy, una forma probada de perder grasa, aunque sea un enfoque extremo.

Cuando una persona se abstiene de comer, el cuerpo tiene que descomponer el tejido corporal para utilizarlo para la supervivencia. La mayor parte de este combustible proviene de la energía almacenada en forma de reservas de grasa corporal. Desafortunadamente, un ayuno severo también es un ayuno peligroso, ya que el cuerpo...

también recurre a otros tejidos para ser utilizados como combustible. Con el ayuno, el cuerpo elige una mezcla de grasa corporal almacenada y masa corporal magra como combustible. La masa corporal magra se utiliza fácilmente como energía. Al igual que el cuerpo recurre a la grasa corporal y la descompone para usarla como energía, puede hacer lo mismo con los músculos y los órganos. Cuando se le priva de alimento, el cuerpo puede descomponer fácilmente el corazón, el hígado y otros órganos para fabricar combustible. El cuerpo también destruirá los músculos de todo el organismo para obtener energía durante un ayuno por inanición. Si bien la grasa se quema rápidamente como combustible, el músculo y los órganos también se queman. Esto puede conducir al agotamiento y, eventualmente, a la muerte. Por lo tanto, podemos concluir que el ayuno, aunque es espiritualmente ventajoso, no es exactamente el enfoque más inteligente para perder grasa.

Una vez que la gente comprendió que el ayuno prolongado funcionaba, pero que el aspecto negativo era la muerte, empezaron a alterar el enfoque del ayuno para la pérdida de peso. Así nació el ayuno modificado. El ayuno modificado consistía en abstenerse de comer por completo durante todo el tiempo que se pudiera, y cuando finalmente uno se rendía, con la fuerza de voluntad destrozada y el apetito gritando a toda marcha, comía. Algunos comían una cantidad pequeña y bebían muchísima agua para suprimir el apetito, pero otros se volvían locos, perdían el control y comían como si fuera su última cena sobre la tierra, probablemente anulando cualquier pérdida de grasa lograda durante los días de ayuno.

Con los avances de la ciencia, el hombre "descubrió" la caloría y comenzó la interminable tarea de tabular números, llevar registros y evitar las porciones grandes. Sin embargo, el que hacía dieta no sabía cuántas calorías necesitaba en un día, así que, con la esperanza de perder grasa y con poco conocimiento, recurrió a un método que todavía prevalece hoy en día. Ese método consiste en: "Si no estás seguro de cuántas calorías deberías comer para perder peso, simplemente toma la ruta conservadora y come menos". Para muchos, el número mágico de 1000 parecía ser lo suficientemente bajo como para funcionar, y muchos de los que siguieron una dieta de solo 1000 calorías al día perdieron peso.

Muchos de los que eligieron el enfoque de 1000 calorías al día pronto descubrieron lo que los científicos demostrarían muchos años después: el temido estancamiento (plateau) en la dieta. La ciencia ha demostrado que cuando se restringen las calorías, el cuerpo compensa obteniendo energía de la grasa corporal almacenada. Pero, a medida que las calorías permanecen bajas durante un tiempo prolongado...

Tras un cierto tiempo, el cuerpo genera otra respuesta de adaptación. Ante una restricción calórica prolongada o muy estricta, el cuerpo comenzará a conservar las calorías. Con el tiempo, el enfoque de las 1000 calorías fracasa porque el cuerpo, que no quiere morir como ocurre en un ayuno prolongado y severo, pero que dispone de calorías suficientes para sobrevivir, sacará el máximo partido a esas 1000 calorías ralentizando radicalmente la velocidad a la que las quema. El resultado es que se pierde grasa con un enfoque de muy baja ingesta calórica, pero la dieta acaba dejando de funcionar como lo hacía al principio.

Las primeras investigaciones sobre el metabolismo y la nutrición revelaron muchos conocimientos fisiológicos que las personas que seguían dietas intentaron aprovechar para perder grasa. Desde el primer momento, quienes seguían dietas se dieron cuenta de que comer menos conduce a la pérdida de peso. Sin embargo, las personas más perspicaces se percataron de las limitaciones de la dieta de 1000 calorías. Las investigaciones comenzaron a demostrar que, con la restricción calórica, además de la grasa corporal, también se perdían proteínas corporales, concretamente en forma de masa muscular. Para combatir esto, las personas que seguían una dieta le dieron un simple giro a la dieta de 1000 calorías. Consumían todas las calorías procedentes de alimentos proteicos. La idea era sencilla: contar las calorías y limitar el total a 1000, pero comer solo alimentos proteicos. Las 1000 calorías son lo suficientemente bajas como para que el cuerpo pierda grasa, y comer más proteínas evitaría que el cuerpo utilizara los músculos como combustible. La mentalidad era sencilla: Inundar el cuerpo con alimentos proteicos adicionales como carnes, queso, cerdo, hamburguesas y pollo, pero limitar la ingesta calórica. La proteína adicional evitará que el cuerpo utilice los músculos como combustible, ya que dispone de la materia prima o proteína que necesita en los alimentos. Esto funcionó mejor que el ayuno, pero carecía de variedad y era demasiado difícil de mantener incluso para quienes tenían la mayor fuerza de voluntad.

A principios del siglo XX, los científicos comenzaron a investigar por qué las personas comían en exceso. Se dieron cuenta de que, si comían menos, perderían peso. Así comenzó la búsqueda de pastillas adelgazantes eficaces. Las primeras pastillas adelgazantes se centraban en suprimir el apetito para que se consumiera menos comida. Eran habituales inventos como la benzocaína. Al colocarla sobre la lengua, la benzocaína adormecía las papilas gustativas y dejaba una sensación de hormigueo y extraña en la boca, lo que los científicos esperaban que

suprimir el apetito. A algunos les funcionó, a otros no. Probablemente se podría lograr un éxito similar enjuagándose la boca con jabón cada vez que se sintiera hambre. Sin duda, cualquier sustancia desagradable que altere el sentido del gusto podría impedir que una persona comiera, independientemente de cuál fuera esa sustancia.

Otros enfoques incluían suprimir el apetito estimulando el cerebro. Inicialmente, esto se lograba con la administración de anfetaminas (speed). El speed parece suprimir el apetito al estimular el centro del apetito del cerebro. Además, combate la fatiga al estimular el sistema nervioso. Hasta aquí, parece un descubrimiento monumental y una gran ayuda para quienes hacen dieta. Se pierde peso comiendo menos y se tiene mucha energía. Por desgracia, como ocurre con muchos fármacos, funcionan demasiado bien. La sobreestimulación del sistema nervioso puede provocar muchas enfermedades como esquizofrenia, paranoia, irritabilidad, incapacidad para pensar con claridad y agotamiento total. Se han desarrollado otros fármacos para disminuir el apetito. La mayoría ejerce fuertes efectos estimulantes sobre el sistema nervioso, pero son mucho más seguros que el speed puro. Estos fármacos son similares al speed en su capacidad para suprimir el apetito, aunque se han modificado para que tengan menores efectos estimulantes generales sobre el organismo. Por lo tanto, se cree que son mucho más seguros. Hablaré de muchas de ellas en el capítulo 15 sobre drogas.

En su momento, los medicamentos para aumentar la cantidad de calorías quemadas gozaban de gran popularidad entre los profesionales de la medicina. Las hormonas tiroideas regulan la cantidad de energía que el cuerpo consume a lo largo del día. Los suplementos de tiroides podrían aumentar la tasa metabólica, pero el cuerpo se adapta fácilmente a las cantidades artificialmente elevadas de tiroides que toma el paciente. En personas sanas, el cuerpo libera la hormona tiroidea en la sangre y esta se transforma en una forma más activa que utilizan los tejidos corporales. Cuando un paciente, con la esperanza de perder grasa, toma medicación tiroidea, el cuerpo acaba respondiendo y adaptándose ralentizando la conversión de la hormona artificial a la forma más activa en el organismo. Además, se suprime la propia liberación de esta hormona por parte del cuerpo. Cualquier aumento del metabolismo no perdura. Quienes intentan aumentar drásticamente la medicación tiroidea para forzar al cuerpo a acelerar el metabolismo,

en última instancia fracasan, ya que altas cantidades de tiroides ejercerán efectos similares a un ayuno modificado. Se pierde grasa, pero el tejido muscular y los órganos se destruyen y descomponen para ser utilizados como combustible.

Los científicos pronto descubrieron un fenómeno especial que se produce con la ingesta de alimentos llamado termogénesis. Termogénesis es una palabra elegante para calor. Los alimentos son en realidad formas de energía. Cuando se ingieren alimentos, el cuerpo descompone el combustible de los mismos para obtener esta energía que le permite mantener la vida y realizar un trabajo. El destino de esta energía es triple. El cuerpo puede utilizarla, puede almacenarla en forma de glucógeno muscular para utilizarla más adelante o puede almacenarla en forma de grasa corporal. El tercer destino de la energía derivada de los alimentos es que puede "desperdiciarse en forma de calor". El cuerpo siempre está produciendo calor, como un horno. Cuando se consumen alimentos, la temperatura corporal aumenta y algunas de las calorías de los alimentos que ingerimos simplemente se queman en forma de calor, dejando menos calorías "netas" disponibles para el cuerpo, las células musculares y las células grasas. Algunos alimentos ejercen un fuerte efecto térmico, mientras que otros no. En concreto, los alimentos proteicos son los que ejercen un mayor efecto térmico. Aproximadamente el 20% de las calorías derivadas de los alimentos proteicos no están disponibles para ser utilizadas por el organismo porque se queman en forma de calor corporal. Por supuesto, los que hacían dieta adoptaron este hecho y, una vez más, las proteínas se convirtieron en el alimento preferido de los que hacían dieta. La gente comía muchas proteínas con la esperanza de que tuvieran un efecto termogénico. Al igual que con cualquier dieta baja en calorías, el enfoque funcionó hasta cierto punto, principalmente debido a una menor ingesta calórica total.

Con el tiempo, a medida que las personas que hacían dieta fracasaban en su búsqueda de un cuerpo esbelto, los psicólogos postularon la teoría de que las personas comen en exceso o en defecto debido a su estado emocional. Algunos estudios mostraron una correlación entre la depresión y comer en exceso. Los psicólogos razonaron que una persona sólo podía librarse de comer en exceso con una terapia intensiva. Una vez detectado y tratado el problema psicológico subyacente, el paciente volvería a comer con normalidad. Aunque la terapia puede ser útil para algunos, no tuvo en cuenta el hecho de que hay millones de personas con sobrepeso que parecen estar perfectamente satisfechas con sus vidas, y muchos que no pueden perder peso y que han realizado años de terapia exhaustiva. Hasta cierto punto, he estado involucrado y encaprichado con

control de la grasa corporal durante 15 años. Las dietas van y vienen. La dieta del arroz, la dieta de la fruta, la dieta baja en carbohidratos, la dieta alta en carbohidratos, la dieta alta en grasas, la dieta baja en grasas, la dieta de la fibra, y la lista continúa. Lo que todas y cada una de las dietas tienen en común es una ingesta calórica controlada. Una cosa que sabemos con certeza, cuando se reducen las calorías, el cuerpo recurre a otras fuentes de combustible, una de ellas es la grasa corporal almacenada. Así que, a diferencia de otros que dicen: "Las dietas no funcionan", yo discrepo y digo: "¡Todas las dietas funcionan!". El problema es el siguiente. O bien son difíciles de mantener durante largos periodos de tiempo, o bien no aportan suficientes calorías, por lo que la persona que hace dieta, desanimada, suele tirar la toalla y abandonar.

Mi primera dieta me la usurpó mi hermana. Ella adelgazó mucho, y a mí no me gustaba mi aspecto y pensé que me sentiría mejor quitándome algo de grasa sobrante. Como cualquier persona a dieta, la única información que conocía eran las "calorías". Las calorías, me decía mi hermana, provocaban la acumulación de grasa corporal. Siendo joven e ingenua, me propuse librarme de las calorías. Dejé de comer, salvo un huevo y una tostada para desayunar, nada para comer, y ensalada y pollo para cenar. Rápidamente perdí 13 libras. Me sentí muy bien cuando pude ponerme ropa que antes me quedaba demasiado ajustada, pero me agoté y me volví muy irritable y mezquina. La dieta dejó de ser una dieta cuando me derrumbé y me aniquilé a mí misma con un torrente interminable de comida: galletas, helado, tarta, pizza, etc., todo en un periodo de 6 horas. Me sentí muy enfadada, desanimada y disgustada. En lugar de volver a la dieta que era severa, pero que estaba logrando lo que yo quería, engordé 15 libras en unas pocas semanas comiendo relativamente normal. Ahora, un kilo más gorda que cuando empecé mi primera dieta, empecé a pensar en una estrategia. Necesitaba una nueva dieta, una mejor. Mirara donde mirara, desde el periódico a las revistas, pasando por la biblioteca y las librerías, encontré infinidad de libros sobre el confuso tema de la pérdida de peso. Lo compré todo. Lo leí todo. Pensaba que podría absorber y digerir toda la información disponible sobre dietas y convertirme en una autoridad. Seguramente, si leía todo lo disponible sobre el tema de la pérdida de peso, podría descubrir o encontrar las mejores dietas y descartar las malas. Bueno, al hacerlo, me confundí más, como estoy seguro de que muchos de ustedes están en este momento.