== Todo lo que necesitas saber sobre la pérdida de peso

¿Por qué otro libro sobre la pérdida de peso, la pérdida de grasa corporal y la dieta? ¡Seguro que ya hay suficientes!

Basta con echar un vistazo a la gran librería de su localidad para sentirse abrumado por la cantidad de libros que orientan, prescriben y venden los últimos consejos, información, investigaciones, ideas, pociones, pastillas y promesas relativas a la pérdida de grasa.

Me parece que gran parte de la información sobre la pérdida de peso es contradictoria, confusa, abrumadora y, en última instancia, puede hacer más daño que bien. Por ejemplo, tenemos la "dieta del arroz" y la "dieta de la fruta". Algunos dicen que la fruta se convierte en grasa, mientras que otros solo comen fruta antes del mediodía. ¿La fruta puede convertirse en grasa en comparación con qué, con los donuts? ¡Creo que no! Nunca he visto a nadie sentarse y comer demasiada fruta, digamos 3 manzanas, una pera y un plátano.

Sin embargo, todos nosotros, en algún momento, nos hemos sentado frente al televisor y engullido una pizza entera, o una caja de galletas, o una montaña de helado. ¿Engorda la fruta? Eres inteligente, dímelo tú. A los que prescriben comer fruta solo antes del mediodía, les digo esto: "¿Y si trabajas en el turno de noche y no te despiertas hasta el mediodía, entonces qué?".

Por supuesto, la dieta baja en grasas, la increíble revelación dietética iniciada por Pritikin, funciona. ¿O no? El enfoque bajo en grasas para perder peso prescribe reducir la ingesta de grasa dietética a menos del 10% del total de calorías. La industria alimentaria ha respondido haciendo que casi todos los productos alimentarios estén disponibles sin grasa o con poca grasa añadida. Ahora, podemos comer pretzels sin grasa, patatas fritas sin grasa, helado sin grasa, pizza sin grasa... sándwiches de atún sin grasa, galletas sin grasa, y la lista continúa. Mi pregunta es esta: con tanto de donde elegir, ¿por qué los estadounidenses somos, en promedio, más gordos que nunca?

Algunos libros de pérdida de peso culpan a tu pereza. Los autores de estos libros suenan algo así: "El ejercicio quema calorías, por lo que realizar suficiente ejercicio mantendrá a una persona delgada o promoverá la pérdida de grasa en todos". Lo siento.

Si bien el ejercicio puede ayudar, no es toda la historia ni la solución definitiva. Lo que comes, la cantidad de calorías totales que consumes y los tipos de alimentos que eliges también tienen un efecto en el almacenamiento de grasa. Algunas personas pueden volverse muy delgadas con el ejercicio, pero otras deberían depender más de la dieta. Además, hay más gimnasios, clubes de salud, centros turísticos, entrenadores personales, máquinas de ejercicio y dispositivos que nunca. Entonces, ¿cuál es la realidad? ¿Cómo es que estamos más gordos que nunca? Es cierto que hay muchos cuerpos asombrosos e increíbles por ahí, pero en conjunto, la población está bastante descuidada.

Sé que estamos fallando la prueba de la grasa cuando veo constantemente niños gordos en centros comerciales, escuelas e iglesias. Claro que había algunos niños robustos cuando yo era joven. Cada escuela tenía su niño gordito que era el blanco de las bromas y del que se burlaban, ¡pero ahora hay tantos!

Hay pastillas para perder grasa, cremas, bebidas, gurús, píldoras con receta, supresores del apetito y terapia. Hay infomerciales nocturnos, dispositivos, clínicas, programas médicos de pérdida de peso, Jenny Craig, Weight Watchers, Slimfast, MetRx, Ensure. Y por si fuera poco, somos bombardeados con estrellas que siempre han parecido delgadas, en forma y esbeltas, vendiendo de todo, desde una máquina para tonificar los muslos hasta un dispositivo de patinaje de interior.

Seguro que también has visto esas máquinas de abdominales en la televisión. Te contaré un secreto: primero, los modelos utilizados para las máquinas de abdominales probablemente nunca en su vida usaron esas máquinas. Segundo, los infomerciales insinúan que podrás lograr unos abdominales de aspecto increíble usando la máquina.  Dudo mucho que eso ocurra.  Para tener los abdominales que tiene el modelo, tendrías que seguir la dieta adecuada para eliminar toda la grasa que cubre la región abdominal y permitir que los abdominales brillen. Después, tendrías que construir los abdominales con ejercicio.

P.T. Barnum fue el creador de la frase: "Cada minuto nace un tonto". Esto era cierto en su época y sigue siéndolo hoy en día. [cite: 1109] Permíteme decirte lo loca que está la industria de las dietas y el ejercicio.

Hace unos años, tuve una reunión con un editor muy prominente de una revista de ejercicios. Durante un almuerzo de negocios, me dijo: "Chris, si quieres ganar dinero, deberías escribir un libro de dietas, pero no un libro de dietas y ejercicios cualquiera. Dale un enfoque extraño, hazlo realmente llamativo y escandaloso. Promete transformaciones de la noche a la mañana, promete resultados instantáneos, promete al lector que esta dieta es secreta, una utilizada por las estrellas de Hollywood y los mejores culturistas profesionales. Dile al lector que asesoras a atletas profesionales, estrellas de cine, incluso políticos".

A medida que me volvía escéptico y mi respeto por este individuo empezaba a cambiar repentinamente mientras hablaba, añadió: "Cuanto más locas parezcan las promesas, más gente comprará. ¡El público comprador es tan malditamente ingenuo, está tan confundido y desesperado que intentará cualquier cosa!".

Después de esa conversación, llamé a mi esposa y acordamos que si alguna vez escribía un libro, sería exactamente lo contrario de la recomendación del rico editor...