== Historia de la pérdida de grasa

Es de sentido común y obvio para mí que la gente ha estado haciendo dieta desde la invención del espejo. La vanidad no es nada nuevo, simplemente se ha magnificado con el tiempo.

Hoy en día, los expertos nos dicen que las personas delgadas viven más tiempo y son más productivas en su vida diaria. Por esta razón, millones de personas se han embarcado en algún tipo de programa de pérdida de peso. Aunque millones de personas hacen dieta y ejercicio para vivir más o para sentirse mejor y tener más energía, supongo que la mayoría lo hace para verse mejor. Aspiramos a la imagen delgada proyectada por quienes vemos en la televisión, en anuncios impresos y en las películas.

Hace años, las personas que querían perder grasa lo hacían basándose en una cantidad muy limitada de información. Antes de la invención de la palabra "caloría", la gente perdía peso mediante el ayuno. El ayuno fue introducido a la humanidad por Dios. Los judíos ayunan, al igual que los cristianos y los musulmanes. Todos lo hacen porque Dios les dijo a los profetas que abstenerse de comer era bueno tanto para el alma como para el cuerpo físico. Un cambio físico común que los tres grupos notaron fue una pérdida de peso, una disminución de la grasa corporal. Por lo tanto, para perder peso, el primer "dietero" se abstenía de comer y bebía agua. Era entonces, y es hoy, una forma probada de perder grasa, aunque sea un enfoque extremo.

Cuando una persona se abstiene de comer, el cuerpo tiene que descomponer el tejido corporal para utilizarlo para la supervivencia. La mayor parte de este combustible proviene de la energía almacenada en forma de reservas de grasa corporal. Desafortunadamente, un ayuno severo también es un ayuno peligroso, ya que el cuerpo...

también recurre a otros tejidos para ser utilizados como combustible. Con el ayuno, el cuerpo elige una mezcla de grasa corporal almacenada y masa corporal magra como combustible. La masa corporal magra se utiliza fácilmente como energía. Al igual que el cuerpo recurre a la grasa corporal y la descompone para usarla como energía, puede hacer lo mismo con los músculos y los órganos. Cuando se le priva de alimento, el cuerpo puede descomponer fácilmente el corazón, el hígado y otros órganos para fabricar combustible. El cuerpo también destruirá los músculos de todo el organismo para obtener energía durante un ayuno por inanición. Si bien la grasa se quema rápidamente como combustible, el músculo y los órganos también se queman. Esto puede conducir al agotamiento y, eventualmente, a la muerte. Por lo tanto, podemos concluir que el ayuno, aunque es espiritualmente ventajoso, no es exactamente el enfoque más inteligente para perder grasa.

Una vez que la gente comprendió que el ayuno prolongado funcionaba, pero que el aspecto negativo era la muerte, empezaron a alterar el enfoque del ayuno para la pérdida de peso. Así nació el ayuno modificado. El ayuno modificado consistía en abstenerse de comer por completo durante todo el tiempo que se pudiera, y cuando finalmente uno se rendía, con la fuerza de voluntad destrozada y el apetito gritando a toda marcha, comía. Algunos comían una cantidad pequeña y bebían muchísima agua para suprimir el apetito, pero otros se volvían locos, perdían el control y comían como si fuera su última cena sobre la tierra, probablemente anulando cualquier pérdida de grasa lograda durante los días de ayuno.

Con los avances de la ciencia, el hombre "descubrió" la caloría y comenzó la interminable tarea de tabular números, llevar registros y evitar las porciones grandes. Sin embargo, el que hacía dieta no sabía cuántas calorías necesitaba en un día, así que, con la esperanza de perder grasa y con poco conocimiento, recurrió a un método que todavía prevalece hoy en día. Ese método consiste en: "Si no estás seguro de cuántas calorías deberías comer para perder peso, simplemente toma la ruta conservadora y come menos". Para muchos, el número mágico de 1000 parecía ser lo suficientemente bajo como para funcionar, y muchos de los que siguieron una dieta de solo 1000 calorías al día perdieron peso.

Muchos de los que eligieron el enfoque de 1000 calorías al día pronto descubrieron lo que los científicos demostrarían muchos años después: el temido estancamiento (plateau) en la dieta. La ciencia ha demostrado que cuando se restringen las calorías, el cuerpo compensa obteniendo energía de la grasa corporal almacenada. Pero, a medida que las calorías permanecen bajas durante un tiempo prolongado...
