== Chapter One: Everything You Need To Know On Weight Loss

Why another book about weight loss, losing body fat, and diet? Surely, there are enough! [cite: 1127, 1129]

Just peruse your local book super store, and you will soon become overwhelmed with the amount of books guiding, prescribing, and selling the latest tips, info, research, ideas, potions, pills and promises pertaining to losing fat. [cite: 1130]

I find much of the weight loss information to be conflicting, confusing, overwhelming, and ultimately can do more harm than good. [cite: 1131] For example, we have the "rice diet" and the "fruit diet." [cite: 1132] Some say fruit turns to fat while others only eat fruits before noon. [cite: 1133] Fruit can turn to fat compared to what, donuts? I think not! [cite: 1134] I never saw anyone sit down and eat too much fruit, say 3 apples a pear and a banana. [cite: 1135]

However, we've all, at some time or another, sat down in front of the TV and gobbled down a whole pizza, or a box of cookies, or a mound of ice cream. [cite: 1136] Is fruit fattening? You're smart, you tell me. For those who prescribe eating fruit only before noon, I say this, "What if you work the late shift and do not wake up until noon, then what?" [cite: 1137]

Of course, the low fat diet, the incredible dietary revelation started by Pritikin works. Or does it? [cite: 1138] The low fat approach to losing weight prescribes lowering your intake of dietary fat to less than 10% of your total calories. [cite: 1139] The food industry has responded by making nearly every food product available with no fat or little fat added. [cite: 1140] Now, we can eat fat free pretzels, fat free potato chips, fat free ice cream, fat free pizza... [cite: 1141]